### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by sp1red** [tetreum/carmechanic#1]
**Not an Issue**    I was wondering if we could colab on this project?

**Comment by tetreum** [comment]
How would you like to collaborate? Are you modeler or do you already have some full car model?

The project would also require some Unity upgrade as i didn't touch it since last commit, hope nothing gets broken.

**Comment by sp1red** [comment]
I already have a full car model made but i did make with the idea of using it in car mechanic simulator 2018 and I also know someone who can do textures and I am a modeler. I have imported to unity 2017.4of1 and it looks like everything works as it should.

**Comment by tetreum** [comment]
Could you share it? So i can see how it fits with the existing code :o

**Comment by sp1red** [comment]
https://drive.google.com/open?id=10tCx2lYsvIpwXMGzZ4RiTVrSO59rAYPa

**Comment by tetreum** [comment]
It doesn't look to be a complete model (no interior, motor, etc..) :( It may work for Car Mechanic Simulator because they already got generic engine pieces models, but i don't, so i can't add the missing parts :(

I've updated the project so it doesn't throw any exception on newest Unity versions.
